# Site settings
title: Lab Quentin Neyraud
baseurl: "/"
baseurl_image: "/static/img/"
url: "http://jekyll-starter.quentinneyraud.fr"

# SEO & head
twitter_username: "@quentin_neyraud"
twitter_creator: "@quentin_neyraud"
meta_description: "This site show all my little experiments"
share_image: "share-image.png"
favicon: "favicon.ico"

# Build settings
markdown: kramdown
source: src
destination: public
host: 0.0.0.0

assets_path: '/build/'
